version: "3"
services:
    redis0:
        image: "redis:alpine"
        ports:
            - "6378:6379"

    redis1:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    redis-queue:
        image: "rq_python:latest"
        command: rq worker --url redis://redis1:6379
        depends_on:
            - redis1
            - redis0
    flask:
        image: "rq_python:latest"
        command: >
            sh -c "service cron start &&
                   echo '0 * * * * rm -rf usr/src/app/app/static/images/wordcloud_images/*' > mycron &&
                   crontab mycron &&
                   rm mycron &&
                   python run.py "
        ports:
            - 5000:5000
        depends_on:
            - redis1
            - redis0
     


