version: "3"

services:

    redis:
        image: "redis:alpine"
        container_name: redis
        ports:
            - "6379:6379"

    redis-queue:
        build: .
        container_name: redis-queue
        volumes:
            - .:/usr/src/app
        command: rq worker --url redis://redis:6379
        depends_on:
            - redis

    flask:
        build: .
        container_name: flask
        restart: always
        volumes:
            - .:/usr/src/app
        command: gunicorn -w 3 run:app -b "0.0.0.0:5000"

        # ports:
        #     - 5000:5000

        # expose to internal containers
        expose:
            - 5000
        depends_on:
            - redis

    nginx:
        build: ./nginx
        container_name: nginx
        restart: always
        volumes:
            - ./app/static:/usr/src/app/app/static
        ports:
            - 80:80
        depends_on: 
            - flask

     


