version: "3"
services:
    redis0:
        image: "redis:alpine"
        ports:
            - "6378:6378"

    redis1:
        image: "redis:alpine"
        ports:
            - "6379:6379"

    redis-queue:
        image: "rq_python:latest"
        command: rq worker --url redis://redis1:6379 redis://redis0:6378
        depends_on:
            - redis1
            - redis0
    flask:
        image: "rq_python:latest"
        command: python run.py
        ports:
            - 5000:5000
        depends_on:
            - redis1
            - redis0
     


